version: 1
defaults:
  commits_per_tick: 200
  enabled: true

repos:
- upstream: optuna/optuna
  loadtest_repo: logic-star-ai-tests/optuna__optuna
  enabled: true
  commits_per_tick: 200
  start_offset: 0
